trigger: none

pool: todo-agent

variables:
  workDir: '$(System.DefaultWorkingDirectory)/Environment/Dev'


stages:
  - stage: INIT
    displayName: 'Terraform Init'
    jobs:
      - job:
        displayName: 'Terraform Init Job'
        steps:
        - task: TerraformTask@5
          displayName: TERRAFORM INIT
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workDir)'
            backendServiceArm: 'todoapp-sp'
            backendAzureRmStorageAccountName: 'todoappinfrastg'
            backendAzureRmContainerName: 'todoapp-infra-ctr'
            backendAzureRmKey: 'dev.terraform.tfstate'
        - publish: $(workDir)
          artifact: terraform-workdir
  - stage: SCAN
    displayName: 'Security Scan'
    dependsOn: INIT
    jobs:
    - job: Scan
      steps:

        - download: current
          artifact: terraform-workdir

        - task: PowerShell@2
          displayName: SCANNING CHECKOV
          inputs:
            targetType: 'inline'
            script: |
              pip install checkov
              checkov -d $(workDir)

        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              Invoke-WebRequest `
                      https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-windows-amd64.exe `
                      -OutFile tfsec.exe
                      .\tfsec.exe $(workDir)

  - stage: PLAN
    displayName: 'Terraform Plan'
    dependsOn: SCAN
    jobs:
    - job: Plan
      steps:

      - download: current
        artifact: terraform-workdir

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(workDir)'
          environmentServiceNameAzureRM: 'todoapp-sp'

  - stage: APPLY
    displayName: 'Terraform Apply'
    dependsOn: PLAN
    condition: succeeded()
    jobs:
    - job: Apply
      displayName: 'Manual Apply'
      pool: todo-agent
      steps:

      - download: current
        artifact: terraform-workdir

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(workDir)'
          environmentServiceNameAzureRM: 'todoapp-sp'
          commandOptions: '-auto-approve'

          
